version: "3.5"
services:

  tile-cache:
    build: .
    environment:
    - TILE_URL=http://10.1.6.1:8800/api/tiles?proxy=true&url=http://mt0.google.com/vt/lyrs=s%26hl=en%26x={x}%26y={y}%26z={z}%26s=Ga
    volumes:
    - ./src:/tile-loader/src
    - sbt-cache:/root/.ivy2
    - tiles:/tile-loader/tiles

volumes:
  sbt-cache:
  tiles: